spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/NOMBRE-BD?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: USUARIO-BD
    password: PASSWORD-BD

server:
  port: 8080                            #AQUI EL PUERTO DONDE QUIERES QUE SE EJECUTE EL TOMCAT INTERNO
  servlet:
    context-path: /servicios            #AQUI EL PATH DONDE INIZIALIZAS LOS CONTROLLERS EJ: localhost:8080/servicios/
